export const FAKE_POPULARS = [
  {
    backdrop_path: "/azWBrlovNOOdy0eQYEe9BoiROoN.jpg",
    first_air_date: "2023-03-20",
    genre_ids: [18, 10766],
    id: 209085,
    name: "Amor Perfeito",
    origin_country: ["BR"],
    original_language: "pt",
    original_name: "Amor Perfeito",
    overview:
      "Amor Perfeito is on of the best shows you will ever see in 2023..!",
    popularity: 1887.458,
    poster_path: "/aOPhyvHDauWFuc3rthpHArCNyrm.jpg",
    vote_average: 9.99,
    vote_count: 19,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/3FLHePl9Y3n4BidLVjIA9qSRDOE.jpg",
    id: 130542,
    name: "Bhagya Lakshmi",
    original_language: "hi",
    original_name: "Bhagya Lakshmi",
    overview:
      "Hailing from a middle-class family, Lakshmi’s life is upended when she realises that her marriage to Rishi Oberoi, an industrialist’s son, is a sham to keep his death at bay.",
    poster_path: "/eVaGfVPA85AUrCAQoOLb0kY2SZA.jpg",
    media_type: "tv",
    genre_ids: [10766],
    popularity: 1329.925,
    first_air_date: "2021-08-03",
    vote_average: 4.56,
    vote_count: 42,
    origin_country: ["IN"],
  },
  {
    adult: false,
    backdrop_path: "/gqxuGoJwzpIfsp2O3N5Ph9k8xfe.jpg",
    id: 134224,
    name: "Voltes V: Legacy",
    original_language: "tl",
    original_name: "Voltes V: Legacy",
    overview:
      "Voltes V: Legacy follows the story of three brothers, Steve, Big Bert, and Little Jon Armstrong, and their friends Jamie Robinson and Mark Gordon, as they fight the forces of humanoid aliens known as Boazanians who plans to invade the earth and launch their beast fighters all over the world.",
    poster_path: "/jZ32tdCTFsRoU2GehW6ZzSpTyS1.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759],
    popularity: 1763.075,
    first_air_date: "2023-05-08",
    vote_average: 4.4,
    vote_count: 5,
    origin_country: ["PH"],
  },
  {
    adult: false,
    backdrop_path: "/mAJ84W6I8I272Da87qplS2Dp9ST.jpg",
    id: 202250,
    name: "Dirty Linen",
    original_language: "tl",
    original_name: "Dirty Linen",
    overview:
      "To exact vengeance, a young woman infiltrates the household of an influential family as a housemaid to expose their dirty secrets. However, love will get in the way of her revenge plot.",
    poster_path: "/aoAZgnmMzY9vVy9VWnO3U5PZENh.jpg",
    media_type: "tv",
    genre_ids: [9648, 18],
    popularity: 2007.851,
    first_air_date: "2023-01-23",
    vote_average: 4.7,
    vote_count: 20,
    origin_country: ["PH"],
  },
  {
    adult: false,
    backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    id: 119051,
    name: "Wednesday",
    original_language: "en",
    original_name: "Wednesday",
    overview:
      "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
    poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    media_type: "tv",
    genre_ids: [10765, 9648, 35],
    popularity: 229.385,
    first_air_date: "2022-11-23",
    vote_average: 8.578,
    vote_count: 7217,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/lerbYAaXFwNh0WpDEpYe5ba0SjK.jpg",
    id: 113988,
    name: "Dahmer – Monster: The Jeffrey Dahmer Story",
    original_language: "en",
    original_name: "Dahmer – Monster: The Jeffrey Dahmer Story",
    overview:
      "This series examines the gruesome and horrific true crimes of Jeffrey Dahmer and the systemic failures that enabled one of America’s most notorious serial killers to continue his murderous spree in plain sight for over a decade.",
    poster_path: "/f2PVrphK0u81ES256lw3oAZuF3x.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 75.677,
    first_air_date: "2022-09-21",
    vote_average: 8.085,
    vote_count: 2128,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/dST2cvC7nBMMmLSONfmSo3drIJI.jpg",
    id: 207863,
    name: "Anne Rice's Mayfair Witches",
    original_language: "en",
    original_name: "Anne Rice's Mayfair Witches",
    overview:
      "An intuitive young neurosurgeon discovers that she is the unlikely heir to a family of witches. As she grapples with her newfound powers, she must contend with a sinister presence that has haunted her family for generations.",
    poster_path: "/zKRBfuRWGbs9R2nxhlNP8CfArUh.jpg",
    media_type: "tv",
    genre_ids: [18, 10765],
    popularity: 84.375,
    first_air_date: "2023-01-08",
    vote_average: 7.2,
    vote_count: 99,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/hIZFG7MK4leU4axRFKJWqrjhmxZ.jpg",
    id: 95403,
    name: "The Peripheral",
    original_language: "en",
    original_name: "The Peripheral",
    overview:
      "Stuck in a small Appalachian town, a young woman’s only escape from the daily grind is playing advanced video games. She is such a good player that a company sends her a new video game system to test…but it has a surprise in store. It unlocks all of her dreams of finding a purpose, romance, and glamour in what seems like a game…but it also puts her and her family in real danger.",
    poster_path: "/2e5NNQu9B1fXBNllRj8fzysCguP.jpg",
    media_type: "tv",
    genre_ids: [10765, 18],
    popularity: 94.532,
    first_air_date: "2022-10-20",
    vote_average: 7.946,
    vote_count: 735,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/6Lw54zxm6BAEKJeGlabyzzR5Juu.jpg",
    id: 82856,
    name: "The Mandalorian",
    original_language: "en",
    original_name: "The Mandalorian",
    overview:
      "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
    poster_path: "/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759, 18],
    popularity: 200.474,
    first_air_date: "2019-11-12",
    vote_average: 8.469,
    vote_count: 9147,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/2meX1nMdScFOoV4370rqHWKmXhY.jpg",
    id: 93405,
    name: "Squid Game",
    original_language: "ko",
    original_name: "오징어 게임",
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games—with high stakes. But, a tempting prize awaits the victor.",
    poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    media_type: "tv",
    genre_ids: [10759, 9648, 18],
    popularity: 138.472,
    first_air_date: "2021-09-17",
    vote_average: 7.832,
    vote_count: 12766,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/uJ16DD1dj4CQLPNCWIoiOF3l8np.jpg",
    id: 100088,
    name: "The Last of Us",
    original_language: "en",
    original_name: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 239.569,
    first_air_date: "2023-01-15",
    vote_average: 8.7,
    vote_count: 3665,
    origin_country: ["US"],
  },
];
